### ISSUE TITLE
Improve session timeout testing and add protection for spam handshakes

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/ddht#228]
## What was wrong?
In #209 - sessions will only timeout if the handshake has not been completed. The testing around session timeout is insufficient to determine that we actively timeout a session before the handshake is able to complete. [discussion](https://github.com/ethereum/ddht/pull/209#pullrequestreview-536602797). 

## How can it be fixed?
Update the [test](https://github.com/ethereum/ddht/blob/master/tests/core/v5_1/test_dispatcher_session_management.py#L7) to validate that the proper `session_timeout` event is emitted when a session times out due to a lack of response - for both the recipient and initiator.

This will likely need to be done by manually initiating the handshake and then halting it before completion since the `Client` APIs do not provide a reliable mechanism for halting a handshake midway.

**Comment by pipermerriam** [comment]
I identified another improvement that will help mitigate this attack vector.

https://github.com/ethereum/ddht/blob/2f52f321bd57738ff354fb37b394318736810f15/ddht/v5_1/dispatcher.py#L271-L285

This function is sub-optimal as the running coroutine will wait longer than it needs to wait in the case where the handshake completes quickly.  This means that if we initiate a lot of handshakes, even if they all complete quickly, we'll accumulate a large number of waiting processes that are not strictly necessary.

What needs to be done is to change the mechanism.

```python
def _wait_handshake_completion(session: SessionAPI):
    with trio.move_on_after(SESSION_TIMEOUT_SECONDS) as scope:
        await session.wait_handshake_complete()
    if scope.cancel_caught:
        ...  # remove session and emit the session timeout event.
```

Alongside this, we need to run these in a nursery.  At present, they get run as child tasks to the `Dispatcher` service.  Recently, we instituted a cap to the number of child tasks a service may run.  This limit is being hit right now in production.

The function above gets run in these two places:

- https://github.com/ethereum/ddht/blob/c68797de8f2a79d18e244afcc87d43029a2505c3/ddht/v5_1/dispatcher.py#L317
- https://github.com/ethereum/ddht/blob/c68797de8f2a79d18e244afcc87d43029a2505c3/ddht/v5_1/dispatcher.py#L344

We should instead switch to use the `Events` API to listen for newly created sessions instead of manually doing this at these call sites.

```python
class Dispatcher:
    def _monitor_new_sessions(self) -> None:
        async with trio.open_nursery() as nursery:
            async with self.events.session_created.subscribe() as subscription:
                async for session in subscription:
                    nursery.start_soon(self._monitor_session_timeout, session)
```

This way all of these can be run in a single nursery without the overhead of all of the `async-service` mechanisms that aren't necessary for this case.

**Comment by pipermerriam** [comment]
@njgheorghita I think that doing the fix I just outlined will *also* allow you to more easily test sessions being timed out since you can then manually fire the `events.session_created()` event with a running dispatcher and you should be able to then monitor for the timeout without having to actually do any of the manual handshaking stuff that was previously needed (because of how session timeout management was previously managed).

Also, it's sort of medium/high priority because it's causing crashes in production :grimacing:

**Comment by pipermerriam** [comment]
@njgheorghita you can test if your solution is working by pulling down https://github.com/ethereum/ddht/pull/242 and running it with `ddht --protocol-version v5.1`

I've consistently hit the crash within a few minutes.

**Comment by njgheorghita** [comment]
@pipermerriam 👍 I've got it working locally, and I'm no longer hitting the max child task limit - however, at about the same time (within 30 seconds or so) that I was hitting the child task limit, now I'm crashing with this error

https://github.com/ethereum/ddht/blob/2fcfaf7ddcd3805feb58734f2c0d50b76ad887fd/ddht/v5_1/client.py#L392-L395

It seems to me that the session is now timing out, causing this error. What is the desired behavior in case of an invalid response - do we want to still raise an exception?
